name: Create Pull Request to Production

on:
  push:
    branches:
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.MY_PERSONAL_TOKEN }}
          destination_branch: "master"  # Ensure correct target branch
          source_branch: "dev"
          pr_title: "Deploying changes to master"
          pr_body: "A new pull request to merge changes from dev to master"
