name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Production
        run: |
          sshpass -p ${{ secrets.PROD_SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null user@prodgit.devopsjourney.in.net 'cd /var/www/html && git pull origin master'
        env:
          PROD_SSH_PASSWORD: ${{ secrets.PROD_SSH_PASSWORD }}
        continue-on-error: true
        
      - name: Health Check
        run: curl http://prod.devopsjourney.in.net/health
