name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Production
        env:
          SSHPASS: ${{ secrets.PROD_SSH_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@3.110.49.217 'cd /var/www/html/ && git pull --allow-unrelated-histories --no-rebase origin master'


      - name: Post Deployment Check
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://3.110.49.217/health)
          if [ "$response" -ne 200 ]; then
            echo "Health check failed with response $response"
            exit 1
          else
            echo "Health check succeeded with response $response"
          fi
