name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Production
        run: |
          sshpass -p ${{ secrets.PROD_SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no user@prodgit.devopsjourney.in.net 'cd /var/www/html && git pull origin main'
        env:
          PROD_SSH_PASSWORD: ${{ secrets.PROD_SSH_PASSWORD }}

      - name: Post Deployment Check
        run: curl http://prod.devopsjourney.in.net/healthcheck
