name: Deploy to Development Server on Push

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Development Server
        env:
          SSHPASS: ${{ secrets.ROOT_PASS }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@43.204.102.135 'cd /var/www/html/ && git pull --allow-unrelated-histories origin dev'

      - name: Health Check
        run: curl http://43.204.102.135/health
